// flow-typed signature: 70cdbb8086fe04956fa2e9f04d015b40
// flow-typed version: <<STUB>>/babel-preset-expo_v^7.0.0/flow_v0.104.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-preset-expo'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-preset-expo' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-preset-expo/lazy-imports-blacklist' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-preset-expo/index' {
  declare module.exports: $Exports<'babel-preset-expo'>;
}
declare module 'babel-preset-expo/index.js' {
  declare module.exports: $Exports<'babel-preset-expo'>;
}
declare module 'babel-preset-expo/lazy-imports-blacklist.js' {
  declare module.exports: $Exports<'babel-preset-expo/lazy-imports-blacklist'>;
}
