// flow-typed signature: 7b55863002a639c7c17e937c0f0fee99
// flow-typed version: <<STUB>>/expokit_v^36.0.0/flow_v0.121.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'expokit'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'expokit' {
  declare module.exports: any;
}
