// flow-typed signature: aacc79a5a8408bdc0ed8304a01308046
// flow-typed version: <<STUB>>/expokit_v^35.0.3/flow_v0.104.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'expokit'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'expokit' {
  declare module.exports: any;
}
