// flow-typed signature: 1355dab490b6a0d7485e16a15d29af9c
// flow-typed version: <<STUB>>/expo-web-browser_v^7.0.0/flow_v0.104.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'expo-web-browser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'expo-web-browser' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'expo-web-browser/build/ExpoWebBrowser' {
  declare module.exports: any;
}

declare module 'expo-web-browser/build/ExpoWebBrowser.web' {
  declare module.exports: any;
}

declare module 'expo-web-browser/build/WebBrowser' {
  declare module.exports: any;
}

declare module 'expo-web-browser/build/WebBrowser.types' {
  declare module.exports: any;
}

// Filename aliases
declare module 'expo-web-browser/build/ExpoWebBrowser.js' {
  declare module.exports: $Exports<'expo-web-browser/build/ExpoWebBrowser'>;
}
declare module 'expo-web-browser/build/ExpoWebBrowser.web.js' {
  declare module.exports: $Exports<'expo-web-browser/build/ExpoWebBrowser.web'>;
}
declare module 'expo-web-browser/build/WebBrowser.js' {
  declare module.exports: $Exports<'expo-web-browser/build/WebBrowser'>;
}
declare module 'expo-web-browser/build/WebBrowser.types.js' {
  declare module.exports: $Exports<'expo-web-browser/build/WebBrowser.types'>;
}
