// flow-typed signature: 1e4c1d17fef9c9f00705acb57f352141
// flow-typed version: <<STUB>>/expo-blur_v^7.0.0/flow_v0.112.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'expo-blur'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'expo-blur' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'expo-blur/build/BlurView.android' {
  declare module.exports: any;
}

declare module 'expo-blur/build/BlurView.ios' {
  declare module.exports: any;
}

declare module 'expo-blur/build/BlurView.types' {
  declare module.exports: any;
}

declare module 'expo-blur/build/BlurView.web' {
  declare module.exports: any;
}

declare module 'expo-blur/build/getBackgroundColor' {
  declare module.exports: any;
}

declare module 'expo-blur/build' {
  declare module.exports: any;
}

// Filename aliases
declare module 'expo-blur/build/BlurView.android.js' {
  declare module.exports: $Exports<'expo-blur/build/BlurView.android'>;
}
declare module 'expo-blur/build/BlurView.ios.js' {
  declare module.exports: $Exports<'expo-blur/build/BlurView.ios'>;
}
declare module 'expo-blur/build/BlurView.types.js' {
  declare module.exports: $Exports<'expo-blur/build/BlurView.types'>;
}
declare module 'expo-blur/build/BlurView.web.js' {
  declare module.exports: $Exports<'expo-blur/build/BlurView.web'>;
}
declare module 'expo-blur/build/getBackgroundColor.js' {
  declare module.exports: $Exports<'expo-blur/build/getBackgroundColor'>;
}
declare module 'expo-blur/build/index' {
  declare module.exports: $Exports<'expo-blur/build'>;
}
declare module 'expo-blur/build/index.js' {
  declare module.exports: $Exports<'expo-blur/build'>;
}
