// flow-typed signature: 65e2282d42271ad1a243ace74e223d91
// flow-typed version: <<STUB>>/expo-asset_v^7.0.0/flow_v0.112.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'expo-asset'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'expo-asset' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'expo-asset/build/Asset.fx' {
  declare module.exports: any;
}

declare module 'expo-asset/build/Asset' {
  declare module.exports: any;
}

declare module 'expo-asset/build/AssetRegistry' {
  declare module.exports: any;
}

declare module 'expo-asset/build/AssetRegistry.web' {
  declare module.exports: any;
}

declare module 'expo-asset/build/AssetSourceResolver' {
  declare module.exports: any;
}

declare module 'expo-asset/build/AssetSourceResolver.web' {
  declare module.exports: any;
}

declare module 'expo-asset/build/AssetSources' {
  declare module.exports: any;
}

declare module 'expo-asset/build/AssetUris' {
  declare module.exports: any;
}

declare module 'expo-asset/build/EmbeddedAssets' {
  declare module.exports: any;
}

declare module 'expo-asset/build/EmbeddedAssets.web' {
  declare module.exports: any;
}

declare module 'expo-asset/build/ImageAssets' {
  declare module.exports: any;
}

declare module 'expo-asset/build' {
  declare module.exports: any;
}

declare module 'expo-asset/build/PlatformUtils' {
  declare module.exports: any;
}

declare module 'expo-asset/build/PlatformUtils.web' {
  declare module.exports: any;
}

declare module 'expo-asset/build/resolveAssetSource' {
  declare module.exports: any;
}

declare module 'expo-asset/build/resolveAssetSource.web' {
  declare module.exports: any;
}

// Filename aliases
declare module 'expo-asset/build/Asset.fx.js' {
  declare module.exports: $Exports<'expo-asset/build/Asset.fx'>;
}
declare module 'expo-asset/build/Asset.js' {
  declare module.exports: $Exports<'expo-asset/build/Asset'>;
}
declare module 'expo-asset/build/AssetRegistry.js' {
  declare module.exports: $Exports<'expo-asset/build/AssetRegistry'>;
}
declare module 'expo-asset/build/AssetRegistry.web.js' {
  declare module.exports: $Exports<'expo-asset/build/AssetRegistry.web'>;
}
declare module 'expo-asset/build/AssetSourceResolver.js' {
  declare module.exports: $Exports<'expo-asset/build/AssetSourceResolver'>;
}
declare module 'expo-asset/build/AssetSourceResolver.web.js' {
  declare module.exports: $Exports<'expo-asset/build/AssetSourceResolver.web'>;
}
declare module 'expo-asset/build/AssetSources.js' {
  declare module.exports: $Exports<'expo-asset/build/AssetSources'>;
}
declare module 'expo-asset/build/AssetUris.js' {
  declare module.exports: $Exports<'expo-asset/build/AssetUris'>;
}
declare module 'expo-asset/build/EmbeddedAssets.js' {
  declare module.exports: $Exports<'expo-asset/build/EmbeddedAssets'>;
}
declare module 'expo-asset/build/EmbeddedAssets.web.js' {
  declare module.exports: $Exports<'expo-asset/build/EmbeddedAssets.web'>;
}
declare module 'expo-asset/build/ImageAssets.js' {
  declare module.exports: $Exports<'expo-asset/build/ImageAssets'>;
}
declare module 'expo-asset/build/index' {
  declare module.exports: $Exports<'expo-asset/build'>;
}
declare module 'expo-asset/build/index.js' {
  declare module.exports: $Exports<'expo-asset/build'>;
}
declare module 'expo-asset/build/PlatformUtils.js' {
  declare module.exports: $Exports<'expo-asset/build/PlatformUtils'>;
}
declare module 'expo-asset/build/PlatformUtils.web.js' {
  declare module.exports: $Exports<'expo-asset/build/PlatformUtils.web'>;
}
declare module 'expo-asset/build/resolveAssetSource.js' {
  declare module.exports: $Exports<'expo-asset/build/resolveAssetSource'>;
}
declare module 'expo-asset/build/resolveAssetSource.web.js' {
  declare module.exports: $Exports<'expo-asset/build/resolveAssetSource.web'>;
}
