// flow-typed signature: 6147272ca628137e350a9f5715134f49
// flow-typed version: <<STUB>>/expokit_v^36.0.0/flow_v0.112.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'expokit'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'expokit' {
  declare module.exports: any;
}
