// flow-typed signature: 6e5c3019e2973eaaaf984e6c10865abd
// flow-typed version: <<STUB>>/expo-analytics-amplitude_v~8.0.0/flow_v0.112.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'expo-analytics-amplitude'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'expo-analytics-amplitude' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'expo-analytics-amplitude/build/Amplitude' {
  declare module.exports: any;
}

declare module 'expo-analytics-amplitude/build/ExpoAmplitude' {
  declare module.exports: any;
}

declare module 'expo-analytics-amplitude/build/ExpoAmplitude.web' {
  declare module.exports: any;
}

// Filename aliases
declare module 'expo-analytics-amplitude/build/Amplitude.js' {
  declare module.exports: $Exports<'expo-analytics-amplitude/build/Amplitude'>;
}
declare module 'expo-analytics-amplitude/build/ExpoAmplitude.js' {
  declare module.exports: $Exports<'expo-analytics-amplitude/build/ExpoAmplitude'>;
}
declare module 'expo-analytics-amplitude/build/ExpoAmplitude.web.js' {
  declare module.exports: $Exports<'expo-analytics-amplitude/build/ExpoAmplitude.web'>;
}
