// flow-typed signature: 7fb4c629cd6e565f18c44a261e0ad014
// flow-typed version: <<STUB>>/expo-cli_v^3.11.7/flow_v0.112.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'expo-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'expo-cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'expo-cli/bin/expo' {
  declare module.exports: any;
}

declare module 'expo-cli/build/accounts' {
  declare module.exports: any;
}

declare module 'expo-cli/build/appleApi/authenticate' {
  declare module.exports: any;
}

declare module 'expo-cli/build/appleApi/createManagers' {
  declare module.exports: any;
}

declare module 'expo-cli/build/appleApi/distributionCert' {
  declare module.exports: any;
}

declare module 'expo-cli/build/appleApi/ensureAppExists' {
  declare module.exports: any;
}

declare module 'expo-cli/build/appleApi/fastlane' {
  declare module.exports: any;
}

declare module 'expo-cli/build/appleApi' {
  declare module.exports: any;
}

declare module 'expo-cli/build/appleApi/provisioningProfile' {
  declare module.exports: any;
}

declare module 'expo-cli/build/appleApi/provisioningProfileAdhoc' {
  declare module.exports: any;
}

declare module 'expo-cli/build/appleApi/pushKey' {
  declare module.exports: any;
}

declare module 'expo-cli/build/appleApi/setup' {
  declare module.exports: any;
}

declare module 'expo-cli/build/askUser' {
  declare module.exports: any;
}

declare module 'expo-cli/build/CommandError' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/android' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/build-native/Builder' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/build-native' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/build-native/prepare' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/build-native/utils' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/build/AndroidBuilder' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/build/BaseBuilder' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/build/BaseBuilder.types' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/build/BuildError' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/build/constants' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/build' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/build/ios/IOSBuilder' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/build/ios/utils/image' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/build/utils' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/bundle-assets' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/client/clientBuildApi' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/client/generateBundleIdentifier' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/client' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/credentials' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/customize' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/diagnostics' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/doctor' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/eject' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/eject/Eject' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/export' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/fetch/android' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/fetch' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/fetch/ios' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/generate-module' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/generate-module/configureModule' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/generate-module/fetchTemplate' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/generate-module/generateModuleAsync' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/generate-module/ModuleConfiguration' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/generate-module/promptQuestionsAsync' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/google-play/AppSigningOptIn' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/init' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/install' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/ios' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/login' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/logout' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/opt-into-google-play-signing' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/optimize' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/prepare-detached-build' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/publish-info' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/publish-modify' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/publish' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/push-creds' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/register' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/send' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/start' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/start/TerminalUI' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/upgrade' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/upload' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/upload/AndroidUploader' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/upload/BaseUploader' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/upload/IOSUploader' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/upload/utils' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/url' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/utils/cli-table' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/utils/ClientUpgradeUtils' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/utils/ProjectUtils' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/utils/url' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/webhooks' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/whoami' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commonOptions' {
  declare module.exports: any;
}

declare module 'expo-cli/build/credentials/actions/list' {
  declare module.exports: any;
}

declare module 'expo-cli/build/credentials/actions/promptForCredentials' {
  declare module.exports: any;
}

declare module 'expo-cli/build/credentials/api' {
  declare module.exports: any;
}

declare module 'expo-cli/build/credentials/context' {
  declare module.exports: any;
}

declare module 'expo-cli/build/credentials/credentials' {
  declare module.exports: any;
}

declare module 'expo-cli/build/credentials' {
  declare module.exports: any;
}

declare module 'expo-cli/build/credentials/route' {
  declare module.exports: any;
}

declare module 'expo-cli/build/credentials/views/AndroidCredentials' {
  declare module.exports: any;
}

declare module 'expo-cli/build/credentials/views/IosAppCredentials' {
  declare module.exports: any;
}

declare module 'expo-cli/build/credentials/views/IosDistCert' {
  declare module.exports: any;
}

declare module 'expo-cli/build/credentials/views/IosProvisioningProfile' {
  declare module.exports: any;
}

declare module 'expo-cli/build/credentials/views/IosProvisioningProfileAdhoc' {
  declare module.exports: any;
}

declare module 'expo-cli/build/credentials/views/IosPushCredentials' {
  declare module.exports: any;
}

declare module 'expo-cli/build/credentials/views/Select' {
  declare module.exports: any;
}

declare module 'expo-cli/build/credentials/views/SetupIosDist' {
  declare module.exports: any;
}

declare module 'expo-cli/build/credentials/views/SetupIosProvisioningProfile' {
  declare module.exports: any;
}

declare module 'expo-cli/build/credentials/views/SetupIosPush' {
  declare module.exports: any;
}

declare module 'expo-cli/build/exit' {
  declare module.exports: any;
}

declare module 'expo-cli/build/exp' {
  declare module.exports: any;
}

declare module 'expo-cli/build/log' {
  declare module.exports: any;
}

declare module 'expo-cli/build/PackageManager' {
  declare module.exports: any;
}

declare module 'expo-cli/build/printRunInstructionsAsync' {
  declare module.exports: any;
}

declare module 'expo-cli/build/prompt' {
  declare module.exports: any;
}

declare module 'expo-cli/build/sendTo' {
  declare module.exports: any;
}

declare module 'expo-cli/build/update' {
  declare module.exports: any;
}

declare module 'expo-cli/build/urlOpts' {
  declare module.exports: any;
}

declare module 'expo-cli/build/validators' {
  declare module.exports: any;
}

// Filename aliases
declare module 'expo-cli/bin/expo.js' {
  declare module.exports: $Exports<'expo-cli/bin/expo'>;
}
declare module 'expo-cli/build/accounts.js' {
  declare module.exports: $Exports<'expo-cli/build/accounts'>;
}
declare module 'expo-cli/build/appleApi/authenticate.js' {
  declare module.exports: $Exports<'expo-cli/build/appleApi/authenticate'>;
}
declare module 'expo-cli/build/appleApi/createManagers.js' {
  declare module.exports: $Exports<'expo-cli/build/appleApi/createManagers'>;
}
declare module 'expo-cli/build/appleApi/distributionCert.js' {
  declare module.exports: $Exports<'expo-cli/build/appleApi/distributionCert'>;
}
declare module 'expo-cli/build/appleApi/ensureAppExists.js' {
  declare module.exports: $Exports<'expo-cli/build/appleApi/ensureAppExists'>;
}
declare module 'expo-cli/build/appleApi/fastlane.js' {
  declare module.exports: $Exports<'expo-cli/build/appleApi/fastlane'>;
}
declare module 'expo-cli/build/appleApi/index' {
  declare module.exports: $Exports<'expo-cli/build/appleApi'>;
}
declare module 'expo-cli/build/appleApi/index.js' {
  declare module.exports: $Exports<'expo-cli/build/appleApi'>;
}
declare module 'expo-cli/build/appleApi/provisioningProfile.js' {
  declare module.exports: $Exports<'expo-cli/build/appleApi/provisioningProfile'>;
}
declare module 'expo-cli/build/appleApi/provisioningProfileAdhoc.js' {
  declare module.exports: $Exports<'expo-cli/build/appleApi/provisioningProfileAdhoc'>;
}
declare module 'expo-cli/build/appleApi/pushKey.js' {
  declare module.exports: $Exports<'expo-cli/build/appleApi/pushKey'>;
}
declare module 'expo-cli/build/appleApi/setup.js' {
  declare module.exports: $Exports<'expo-cli/build/appleApi/setup'>;
}
declare module 'expo-cli/build/askUser.js' {
  declare module.exports: $Exports<'expo-cli/build/askUser'>;
}
declare module 'expo-cli/build/CommandError.js' {
  declare module.exports: $Exports<'expo-cli/build/CommandError'>;
}
declare module 'expo-cli/build/commands/android.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/android'>;
}
declare module 'expo-cli/build/commands/build-native/Builder.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/build-native/Builder'>;
}
declare module 'expo-cli/build/commands/build-native/index' {
  declare module.exports: $Exports<'expo-cli/build/commands/build-native'>;
}
declare module 'expo-cli/build/commands/build-native/index.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/build-native'>;
}
declare module 'expo-cli/build/commands/build-native/prepare.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/build-native/prepare'>;
}
declare module 'expo-cli/build/commands/build-native/utils.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/build-native/utils'>;
}
declare module 'expo-cli/build/commands/build/AndroidBuilder.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/build/AndroidBuilder'>;
}
declare module 'expo-cli/build/commands/build/BaseBuilder.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/build/BaseBuilder'>;
}
declare module 'expo-cli/build/commands/build/BaseBuilder.types.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/build/BaseBuilder.types'>;
}
declare module 'expo-cli/build/commands/build/BuildError.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/build/BuildError'>;
}
declare module 'expo-cli/build/commands/build/constants.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/build/constants'>;
}
declare module 'expo-cli/build/commands/build/index' {
  declare module.exports: $Exports<'expo-cli/build/commands/build'>;
}
declare module 'expo-cli/build/commands/build/index.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/build'>;
}
declare module 'expo-cli/build/commands/build/ios/IOSBuilder.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/build/ios/IOSBuilder'>;
}
declare module 'expo-cli/build/commands/build/ios/utils/image.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/build/ios/utils/image'>;
}
declare module 'expo-cli/build/commands/build/utils.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/build/utils'>;
}
declare module 'expo-cli/build/commands/bundle-assets.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/bundle-assets'>;
}
declare module 'expo-cli/build/commands/client/clientBuildApi.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/client/clientBuildApi'>;
}
declare module 'expo-cli/build/commands/client/generateBundleIdentifier.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/client/generateBundleIdentifier'>;
}
declare module 'expo-cli/build/commands/client/index' {
  declare module.exports: $Exports<'expo-cli/build/commands/client'>;
}
declare module 'expo-cli/build/commands/client/index.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/client'>;
}
declare module 'expo-cli/build/commands/credentials.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/credentials'>;
}
declare module 'expo-cli/build/commands/customize.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/customize'>;
}
declare module 'expo-cli/build/commands/diagnostics.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/diagnostics'>;
}
declare module 'expo-cli/build/commands/doctor.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/doctor'>;
}
declare module 'expo-cli/build/commands/eject.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/eject'>;
}
declare module 'expo-cli/build/commands/eject/Eject.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/eject/Eject'>;
}
declare module 'expo-cli/build/commands/export.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/export'>;
}
declare module 'expo-cli/build/commands/fetch/android.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/fetch/android'>;
}
declare module 'expo-cli/build/commands/fetch/index' {
  declare module.exports: $Exports<'expo-cli/build/commands/fetch'>;
}
declare module 'expo-cli/build/commands/fetch/index.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/fetch'>;
}
declare module 'expo-cli/build/commands/fetch/ios.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/fetch/ios'>;
}
declare module 'expo-cli/build/commands/generate-module.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/generate-module'>;
}
declare module 'expo-cli/build/commands/generate-module/configureModule.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/generate-module/configureModule'>;
}
declare module 'expo-cli/build/commands/generate-module/fetchTemplate.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/generate-module/fetchTemplate'>;
}
declare module 'expo-cli/build/commands/generate-module/generateModuleAsync.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/generate-module/generateModuleAsync'>;
}
declare module 'expo-cli/build/commands/generate-module/ModuleConfiguration.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/generate-module/ModuleConfiguration'>;
}
declare module 'expo-cli/build/commands/generate-module/promptQuestionsAsync.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/generate-module/promptQuestionsAsync'>;
}
declare module 'expo-cli/build/commands/google-play/AppSigningOptIn.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/google-play/AppSigningOptIn'>;
}
declare module 'expo-cli/build/commands/index' {
  declare module.exports: $Exports<'expo-cli/build/commands'>;
}
declare module 'expo-cli/build/commands/index.js' {
  declare module.exports: $Exports<'expo-cli/build/commands'>;
}
declare module 'expo-cli/build/commands/init.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/init'>;
}
declare module 'expo-cli/build/commands/install.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/install'>;
}
declare module 'expo-cli/build/commands/ios.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/ios'>;
}
declare module 'expo-cli/build/commands/login.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/login'>;
}
declare module 'expo-cli/build/commands/logout.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/logout'>;
}
declare module 'expo-cli/build/commands/opt-into-google-play-signing.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/opt-into-google-play-signing'>;
}
declare module 'expo-cli/build/commands/optimize.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/optimize'>;
}
declare module 'expo-cli/build/commands/prepare-detached-build.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/prepare-detached-build'>;
}
declare module 'expo-cli/build/commands/publish-info.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/publish-info'>;
}
declare module 'expo-cli/build/commands/publish-modify.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/publish-modify'>;
}
declare module 'expo-cli/build/commands/publish.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/publish'>;
}
declare module 'expo-cli/build/commands/push-creds.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/push-creds'>;
}
declare module 'expo-cli/build/commands/register.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/register'>;
}
declare module 'expo-cli/build/commands/send.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/send'>;
}
declare module 'expo-cli/build/commands/start.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/start'>;
}
declare module 'expo-cli/build/commands/start/TerminalUI.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/start/TerminalUI'>;
}
declare module 'expo-cli/build/commands/upgrade.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/upgrade'>;
}
declare module 'expo-cli/build/commands/upload.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/upload'>;
}
declare module 'expo-cli/build/commands/upload/AndroidUploader.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/upload/AndroidUploader'>;
}
declare module 'expo-cli/build/commands/upload/BaseUploader.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/upload/BaseUploader'>;
}
declare module 'expo-cli/build/commands/upload/IOSUploader.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/upload/IOSUploader'>;
}
declare module 'expo-cli/build/commands/upload/utils.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/upload/utils'>;
}
declare module 'expo-cli/build/commands/url.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/url'>;
}
declare module 'expo-cli/build/commands/utils/cli-table.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/utils/cli-table'>;
}
declare module 'expo-cli/build/commands/utils/ClientUpgradeUtils.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/utils/ClientUpgradeUtils'>;
}
declare module 'expo-cli/build/commands/utils/ProjectUtils.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/utils/ProjectUtils'>;
}
declare module 'expo-cli/build/commands/utils/url.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/utils/url'>;
}
declare module 'expo-cli/build/commands/webhooks.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/webhooks'>;
}
declare module 'expo-cli/build/commands/whoami.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/whoami'>;
}
declare module 'expo-cli/build/commonOptions.js' {
  declare module.exports: $Exports<'expo-cli/build/commonOptions'>;
}
declare module 'expo-cli/build/credentials/actions/list.js' {
  declare module.exports: $Exports<'expo-cli/build/credentials/actions/list'>;
}
declare module 'expo-cli/build/credentials/actions/promptForCredentials.js' {
  declare module.exports: $Exports<'expo-cli/build/credentials/actions/promptForCredentials'>;
}
declare module 'expo-cli/build/credentials/api.js' {
  declare module.exports: $Exports<'expo-cli/build/credentials/api'>;
}
declare module 'expo-cli/build/credentials/context.js' {
  declare module.exports: $Exports<'expo-cli/build/credentials/context'>;
}
declare module 'expo-cli/build/credentials/credentials.js' {
  declare module.exports: $Exports<'expo-cli/build/credentials/credentials'>;
}
declare module 'expo-cli/build/credentials/index' {
  declare module.exports: $Exports<'expo-cli/build/credentials'>;
}
declare module 'expo-cli/build/credentials/index.js' {
  declare module.exports: $Exports<'expo-cli/build/credentials'>;
}
declare module 'expo-cli/build/credentials/route.js' {
  declare module.exports: $Exports<'expo-cli/build/credentials/route'>;
}
declare module 'expo-cli/build/credentials/views/AndroidCredentials.js' {
  declare module.exports: $Exports<'expo-cli/build/credentials/views/AndroidCredentials'>;
}
declare module 'expo-cli/build/credentials/views/IosAppCredentials.js' {
  declare module.exports: $Exports<'expo-cli/build/credentials/views/IosAppCredentials'>;
}
declare module 'expo-cli/build/credentials/views/IosDistCert.js' {
  declare module.exports: $Exports<'expo-cli/build/credentials/views/IosDistCert'>;
}
declare module 'expo-cli/build/credentials/views/IosProvisioningProfile.js' {
  declare module.exports: $Exports<'expo-cli/build/credentials/views/IosProvisioningProfile'>;
}
declare module 'expo-cli/build/credentials/views/IosProvisioningProfileAdhoc.js' {
  declare module.exports: $Exports<'expo-cli/build/credentials/views/IosProvisioningProfileAdhoc'>;
}
declare module 'expo-cli/build/credentials/views/IosPushCredentials.js' {
  declare module.exports: $Exports<'expo-cli/build/credentials/views/IosPushCredentials'>;
}
declare module 'expo-cli/build/credentials/views/Select.js' {
  declare module.exports: $Exports<'expo-cli/build/credentials/views/Select'>;
}
declare module 'expo-cli/build/credentials/views/SetupIosDist.js' {
  declare module.exports: $Exports<'expo-cli/build/credentials/views/SetupIosDist'>;
}
declare module 'expo-cli/build/credentials/views/SetupIosProvisioningProfile.js' {
  declare module.exports: $Exports<'expo-cli/build/credentials/views/SetupIosProvisioningProfile'>;
}
declare module 'expo-cli/build/credentials/views/SetupIosPush.js' {
  declare module.exports: $Exports<'expo-cli/build/credentials/views/SetupIosPush'>;
}
declare module 'expo-cli/build/exit.js' {
  declare module.exports: $Exports<'expo-cli/build/exit'>;
}
declare module 'expo-cli/build/exp.js' {
  declare module.exports: $Exports<'expo-cli/build/exp'>;
}
declare module 'expo-cli/build/log.js' {
  declare module.exports: $Exports<'expo-cli/build/log'>;
}
declare module 'expo-cli/build/PackageManager.js' {
  declare module.exports: $Exports<'expo-cli/build/PackageManager'>;
}
declare module 'expo-cli/build/printRunInstructionsAsync.js' {
  declare module.exports: $Exports<'expo-cli/build/printRunInstructionsAsync'>;
}
declare module 'expo-cli/build/prompt.js' {
  declare module.exports: $Exports<'expo-cli/build/prompt'>;
}
declare module 'expo-cli/build/sendTo.js' {
  declare module.exports: $Exports<'expo-cli/build/sendTo'>;
}
declare module 'expo-cli/build/update.js' {
  declare module.exports: $Exports<'expo-cli/build/update'>;
}
declare module 'expo-cli/build/urlOpts.js' {
  declare module.exports: $Exports<'expo-cli/build/urlOpts'>;
}
declare module 'expo-cli/build/validators.js' {
  declare module.exports: $Exports<'expo-cli/build/validators'>;
}
