// flow-typed signature: 552b4092e82aa2383634e29a53b4aef6
// flow-typed version: <<STUB>>/expo-font_v~8.0.0/flow_v0.120.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'expo-font'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'expo-font' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'expo-font/build/ExpoFontLoader' {
  declare module.exports: any;
}

declare module 'expo-font/build/ExpoFontLoader.web' {
  declare module.exports: any;
}

declare module 'expo-font/build/Font' {
  declare module.exports: any;
}

declare module 'expo-font/build/Font.types' {
  declare module.exports: any;
}

declare module 'expo-font/build/FontLoader' {
  declare module.exports: any;
}

declare module 'expo-font/build/FontLoader.web' {
  declare module.exports: any;
}

// Filename aliases
declare module 'expo-font/build/ExpoFontLoader.js' {
  declare module.exports: $Exports<'expo-font/build/ExpoFontLoader'>;
}
declare module 'expo-font/build/ExpoFontLoader.web.js' {
  declare module.exports: $Exports<'expo-font/build/ExpoFontLoader.web'>;
}
declare module 'expo-font/build/Font.js' {
  declare module.exports: $Exports<'expo-font/build/Font'>;
}
declare module 'expo-font/build/Font.types.js' {
  declare module.exports: $Exports<'expo-font/build/Font.types'>;
}
declare module 'expo-font/build/FontLoader.js' {
  declare module.exports: $Exports<'expo-font/build/FontLoader'>;
}
declare module 'expo-font/build/FontLoader.web.js' {
  declare module.exports: $Exports<'expo-font/build/FontLoader.web'>;
}
