// flow-typed signature: 15e991dc62c5f7a2c1c16ee461be9f77
// flow-typed version: <<STUB>>/fast-html-parser_v^1.0.1/flow_v0.121.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fast-html-parser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fast-html-parser' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fast-html-parser/test/html' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fast-html-parser/index' {
  declare module.exports: $Exports<'fast-html-parser'>;
}
declare module 'fast-html-parser/index.js' {
  declare module.exports: $Exports<'fast-html-parser'>;
}
declare module 'fast-html-parser/test/html.js' {
  declare module.exports: $Exports<'fast-html-parser/test/html'>;
}
