// flow-typed signature: 899203cbf7159ce8a821afc0202d9cb2
// flow-typed version: <<STUB>>/jest-expo_v^36.0.0/flow_v0.112.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-expo'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-expo' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-expo/android/jest-preset' {
  declare module.exports: any;
}

declare module 'jest-expo/bin/jest' {
  declare module.exports: any;
}

declare module 'jest-expo/config/getPlatformPreset' {
  declare module.exports: any;
}

declare module 'jest-expo/config' {
  declare module.exports: any;
}

declare module 'jest-expo/config/withWatchPlugins' {
  declare module.exports: any;
}

declare module 'jest-expo/ios/jest-preset' {
  declare module.exports: any;
}

declare module 'jest-expo/jest-preset' {
  declare module.exports: any;
}

declare module 'jest-expo/node/jest-preset' {
  declare module.exports: any;
}

declare module 'jest-expo/src' {
  declare module.exports: any;
}

declare module 'jest-expo/src/preset/assetFileTransformer' {
  declare module.exports: any;
}

declare module 'jest-expo/src/preset/createMockConstants' {
  declare module.exports: any;
}

declare module 'jest-expo/src/preset/expoModules' {
  declare module.exports: any;
}

declare module 'jest-expo/src/preset/internalExpoModules' {
  declare module.exports: any;
}

declare module 'jest-expo/src/preset/setup' {
  declare module.exports: any;
}

declare module 'jest-expo/src/snapshot/createPlatformResolver' {
  declare module.exports: any;
}

declare module 'jest-expo/src/snapshot/resolver.android' {
  declare module.exports: any;
}

declare module 'jest-expo/src/snapshot/resolver.ios' {
  declare module.exports: any;
}

declare module 'jest-expo/src/snapshot/resolver.node' {
  declare module.exports: any;
}

declare module 'jest-expo/src/snapshot/resolver.web' {
  declare module.exports: any;
}

declare module 'jest-expo/universal/jest-preset' {
  declare module.exports: any;
}

declare module 'jest-expo/web/jest-preset' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-expo/android/jest-preset.js' {
  declare module.exports: $Exports<'jest-expo/android/jest-preset'>;
}
declare module 'jest-expo/bin/jest.js' {
  declare module.exports: $Exports<'jest-expo/bin/jest'>;
}
declare module 'jest-expo/config/getPlatformPreset.js' {
  declare module.exports: $Exports<'jest-expo/config/getPlatformPreset'>;
}
declare module 'jest-expo/config/index' {
  declare module.exports: $Exports<'jest-expo/config'>;
}
declare module 'jest-expo/config/index.js' {
  declare module.exports: $Exports<'jest-expo/config'>;
}
declare module 'jest-expo/config/withWatchPlugins.js' {
  declare module.exports: $Exports<'jest-expo/config/withWatchPlugins'>;
}
declare module 'jest-expo/ios/jest-preset.js' {
  declare module.exports: $Exports<'jest-expo/ios/jest-preset'>;
}
declare module 'jest-expo/jest-preset.js' {
  declare module.exports: $Exports<'jest-expo/jest-preset'>;
}
declare module 'jest-expo/node/jest-preset.js' {
  declare module.exports: $Exports<'jest-expo/node/jest-preset'>;
}
declare module 'jest-expo/src/index' {
  declare module.exports: $Exports<'jest-expo/src'>;
}
declare module 'jest-expo/src/index.js' {
  declare module.exports: $Exports<'jest-expo/src'>;
}
declare module 'jest-expo/src/preset/assetFileTransformer.js' {
  declare module.exports: $Exports<'jest-expo/src/preset/assetFileTransformer'>;
}
declare module 'jest-expo/src/preset/createMockConstants.js' {
  declare module.exports: $Exports<'jest-expo/src/preset/createMockConstants'>;
}
declare module 'jest-expo/src/preset/expoModules.js' {
  declare module.exports: $Exports<'jest-expo/src/preset/expoModules'>;
}
declare module 'jest-expo/src/preset/internalExpoModules.js' {
  declare module.exports: $Exports<'jest-expo/src/preset/internalExpoModules'>;
}
declare module 'jest-expo/src/preset/setup.js' {
  declare module.exports: $Exports<'jest-expo/src/preset/setup'>;
}
declare module 'jest-expo/src/snapshot/createPlatformResolver.js' {
  declare module.exports: $Exports<'jest-expo/src/snapshot/createPlatformResolver'>;
}
declare module 'jest-expo/src/snapshot/resolver.android.js' {
  declare module.exports: $Exports<'jest-expo/src/snapshot/resolver.android'>;
}
declare module 'jest-expo/src/snapshot/resolver.ios.js' {
  declare module.exports: $Exports<'jest-expo/src/snapshot/resolver.ios'>;
}
declare module 'jest-expo/src/snapshot/resolver.node.js' {
  declare module.exports: $Exports<'jest-expo/src/snapshot/resolver.node'>;
}
declare module 'jest-expo/src/snapshot/resolver.web.js' {
  declare module.exports: $Exports<'jest-expo/src/snapshot/resolver.web'>;
}
declare module 'jest-expo/universal/jest-preset.js' {
  declare module.exports: $Exports<'jest-expo/universal/jest-preset'>;
}
declare module 'jest-expo/web/jest-preset.js' {
  declare module.exports: $Exports<'jest-expo/web/jest-preset'>;
}
