// flow-typed signature: f46e9e1132ed96c69029b97f08e86802
// flow-typed version: <<STUB>>/react-native-youtube_v^2.0.0-beta/flow_v0.104.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-youtube'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-youtube' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-youtube/main' {
  declare module.exports: any;
}

declare module 'react-native-youtube/YouTube.android' {
  declare module.exports: any;
}

declare module 'react-native-youtube/YouTube.ios' {
  declare module.exports: any;
}

declare module 'react-native-youtube/YouTubeStandalone.android' {
  declare module.exports: any;
}

declare module 'react-native-youtube/YouTubeStandalone.ios' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-youtube/main.js' {
  declare module.exports: $Exports<'react-native-youtube/main'>;
}
declare module 'react-native-youtube/YouTube.android.js' {
  declare module.exports: $Exports<'react-native-youtube/YouTube.android'>;
}
declare module 'react-native-youtube/YouTube.ios.js' {
  declare module.exports: $Exports<'react-native-youtube/YouTube.ios'>;
}
declare module 'react-native-youtube/YouTubeStandalone.android.js' {
  declare module.exports: $Exports<'react-native-youtube/YouTubeStandalone.android'>;
}
declare module 'react-native-youtube/YouTubeStandalone.ios.js' {
  declare module.exports: $Exports<'react-native-youtube/YouTubeStandalone.ios'>;
}
