// flow-typed signature: adbd2994c6e9e06dbbfb1004edb192e8
// flow-typed version: <<STUB>>/react-native-iphone-x-helper_v^1.2.1/flow_v0.104.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-iphone-x-helper'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-iphone-x-helper' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-native-iphone-x-helper/index' {
  declare module.exports: $Exports<'react-native-iphone-x-helper'>;
}
declare module 'react-native-iphone-x-helper/index.js' {
  declare module.exports: $Exports<'react-native-iphone-x-helper'>;
}
