// flow-typed signature: 755fc72f6f991b1512b900e95a4a31c9
// flow-typed version: <<STUB>>/react-native-svg_v^9.9.9/flow_v0.104.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-svg'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-svg' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-svg/lib/commonjs/elements/Circle' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/commonjs/elements/ClipPath' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/commonjs/elements/Defs' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/commonjs/elements/Ellipse' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/commonjs/elements/G' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/commonjs/elements/Image' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/commonjs/elements/Line' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/commonjs/elements/LinearGradient' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/commonjs/elements/Mask' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/commonjs/elements/Path' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/commonjs/elements/Pattern' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/commonjs/elements/Polygon' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/commonjs/elements/Polyline' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/commonjs/elements/RadialGradient' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/commonjs/elements/Rect' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/commonjs/elements/Shape' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/commonjs/elements/Stop' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/commonjs/elements/Svg' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/commonjs/elements/Symbol' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/commonjs/elements/Text' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/commonjs/elements/TextPath' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/commonjs/elements/TSpan' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/commonjs/elements/Use' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/commonjs/index.d' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/commonjs' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/commonjs/lib/extract/extractBrush' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/commonjs/lib/extract/extractClipPath' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/commonjs/lib/extract/extractColor' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/commonjs/lib/extract/extractFill' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/commonjs/lib/extract/extractGradient' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/commonjs/lib/extract/extractLengthList' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/commonjs/lib/extract/extractOpacity' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/commonjs/lib/extract/extractPolyPoints' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/commonjs/lib/extract/extractProps' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/commonjs/lib/extract/extractResponder' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/commonjs/lib/extract/extractStroke' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/commonjs/lib/extract/extractText' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/commonjs/lib/extract/extractTransform' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/commonjs/lib/extract/extractViewBox' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/commonjs/lib/extract/transform' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/commonjs/lib/extract/types' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/commonjs/lib/Matrix2D' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/commonjs/lib/resolve' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/commonjs/lib/SvgTouchableMixin' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/commonjs/lib/units' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/commonjs/lib/util' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/commonjs/ReactNativeSVG' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/commonjs/ReactNativeSVG.web' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/commonjs/xml' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/module/elements/Circle' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/module/elements/ClipPath' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/module/elements/Defs' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/module/elements/Ellipse' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/module/elements/G' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/module/elements/Image' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/module/elements/Line' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/module/elements/LinearGradient' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/module/elements/Mask' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/module/elements/Path' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/module/elements/Pattern' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/module/elements/Polygon' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/module/elements/Polyline' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/module/elements/RadialGradient' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/module/elements/Rect' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/module/elements/Shape' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/module/elements/Stop' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/module/elements/Svg' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/module/elements/Symbol' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/module/elements/Text' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/module/elements/TextPath' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/module/elements/TSpan' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/module/elements/Use' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/module/index.d' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/module' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/module/lib/extract/extractBrush' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/module/lib/extract/extractClipPath' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/module/lib/extract/extractColor' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/module/lib/extract/extractFill' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/module/lib/extract/extractGradient' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/module/lib/extract/extractLengthList' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/module/lib/extract/extractOpacity' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/module/lib/extract/extractPolyPoints' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/module/lib/extract/extractProps' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/module/lib/extract/extractResponder' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/module/lib/extract/extractStroke' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/module/lib/extract/extractText' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/module/lib/extract/extractTransform' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/module/lib/extract/extractViewBox' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/module/lib/extract/transform' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/module/lib/extract/types' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/module/lib/Matrix2D' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/module/lib/resolve' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/module/lib/SvgTouchableMixin' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/module/lib/units' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/module/lib/util' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/module/ReactNativeSVG' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/module/ReactNativeSVG.web' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/module/xml' {
  declare module.exports: any;
}

declare module 'react-native-svg/src/lib/extract/transform' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-svg/lib/commonjs/elements/Circle.js' {
  declare module.exports: $Exports<'react-native-svg/lib/commonjs/elements/Circle'>;
}
declare module 'react-native-svg/lib/commonjs/elements/ClipPath.js' {
  declare module.exports: $Exports<'react-native-svg/lib/commonjs/elements/ClipPath'>;
}
declare module 'react-native-svg/lib/commonjs/elements/Defs.js' {
  declare module.exports: $Exports<'react-native-svg/lib/commonjs/elements/Defs'>;
}
declare module 'react-native-svg/lib/commonjs/elements/Ellipse.js' {
  declare module.exports: $Exports<'react-native-svg/lib/commonjs/elements/Ellipse'>;
}
declare module 'react-native-svg/lib/commonjs/elements/G.js' {
  declare module.exports: $Exports<'react-native-svg/lib/commonjs/elements/G'>;
}
declare module 'react-native-svg/lib/commonjs/elements/Image.js' {
  declare module.exports: $Exports<'react-native-svg/lib/commonjs/elements/Image'>;
}
declare module 'react-native-svg/lib/commonjs/elements/Line.js' {
  declare module.exports: $Exports<'react-native-svg/lib/commonjs/elements/Line'>;
}
declare module 'react-native-svg/lib/commonjs/elements/LinearGradient.js' {
  declare module.exports: $Exports<'react-native-svg/lib/commonjs/elements/LinearGradient'>;
}
declare module 'react-native-svg/lib/commonjs/elements/Mask.js' {
  declare module.exports: $Exports<'react-native-svg/lib/commonjs/elements/Mask'>;
}
declare module 'react-native-svg/lib/commonjs/elements/Path.js' {
  declare module.exports: $Exports<'react-native-svg/lib/commonjs/elements/Path'>;
}
declare module 'react-native-svg/lib/commonjs/elements/Pattern.js' {
  declare module.exports: $Exports<'react-native-svg/lib/commonjs/elements/Pattern'>;
}
declare module 'react-native-svg/lib/commonjs/elements/Polygon.js' {
  declare module.exports: $Exports<'react-native-svg/lib/commonjs/elements/Polygon'>;
}
declare module 'react-native-svg/lib/commonjs/elements/Polyline.js' {
  declare module.exports: $Exports<'react-native-svg/lib/commonjs/elements/Polyline'>;
}
declare module 'react-native-svg/lib/commonjs/elements/RadialGradient.js' {
  declare module.exports: $Exports<'react-native-svg/lib/commonjs/elements/RadialGradient'>;
}
declare module 'react-native-svg/lib/commonjs/elements/Rect.js' {
  declare module.exports: $Exports<'react-native-svg/lib/commonjs/elements/Rect'>;
}
declare module 'react-native-svg/lib/commonjs/elements/Shape.js' {
  declare module.exports: $Exports<'react-native-svg/lib/commonjs/elements/Shape'>;
}
declare module 'react-native-svg/lib/commonjs/elements/Stop.js' {
  declare module.exports: $Exports<'react-native-svg/lib/commonjs/elements/Stop'>;
}
declare module 'react-native-svg/lib/commonjs/elements/Svg.js' {
  declare module.exports: $Exports<'react-native-svg/lib/commonjs/elements/Svg'>;
}
declare module 'react-native-svg/lib/commonjs/elements/Symbol.js' {
  declare module.exports: $Exports<'react-native-svg/lib/commonjs/elements/Symbol'>;
}
declare module 'react-native-svg/lib/commonjs/elements/Text.js' {
  declare module.exports: $Exports<'react-native-svg/lib/commonjs/elements/Text'>;
}
declare module 'react-native-svg/lib/commonjs/elements/TextPath.js' {
  declare module.exports: $Exports<'react-native-svg/lib/commonjs/elements/TextPath'>;
}
declare module 'react-native-svg/lib/commonjs/elements/TSpan.js' {
  declare module.exports: $Exports<'react-native-svg/lib/commonjs/elements/TSpan'>;
}
declare module 'react-native-svg/lib/commonjs/elements/Use.js' {
  declare module.exports: $Exports<'react-native-svg/lib/commonjs/elements/Use'>;
}
declare module 'react-native-svg/lib/commonjs/index.d.js' {
  declare module.exports: $Exports<'react-native-svg/lib/commonjs/index.d'>;
}
declare module 'react-native-svg/lib/commonjs/index' {
  declare module.exports: $Exports<'react-native-svg/lib/commonjs'>;
}
declare module 'react-native-svg/lib/commonjs/index.js' {
  declare module.exports: $Exports<'react-native-svg/lib/commonjs'>;
}
declare module 'react-native-svg/lib/commonjs/lib/extract/extractBrush.js' {
  declare module.exports: $Exports<'react-native-svg/lib/commonjs/lib/extract/extractBrush'>;
}
declare module 'react-native-svg/lib/commonjs/lib/extract/extractClipPath.js' {
  declare module.exports: $Exports<'react-native-svg/lib/commonjs/lib/extract/extractClipPath'>;
}
declare module 'react-native-svg/lib/commonjs/lib/extract/extractColor.js' {
  declare module.exports: $Exports<'react-native-svg/lib/commonjs/lib/extract/extractColor'>;
}
declare module 'react-native-svg/lib/commonjs/lib/extract/extractFill.js' {
  declare module.exports: $Exports<'react-native-svg/lib/commonjs/lib/extract/extractFill'>;
}
declare module 'react-native-svg/lib/commonjs/lib/extract/extractGradient.js' {
  declare module.exports: $Exports<'react-native-svg/lib/commonjs/lib/extract/extractGradient'>;
}
declare module 'react-native-svg/lib/commonjs/lib/extract/extractLengthList.js' {
  declare module.exports: $Exports<'react-native-svg/lib/commonjs/lib/extract/extractLengthList'>;
}
declare module 'react-native-svg/lib/commonjs/lib/extract/extractOpacity.js' {
  declare module.exports: $Exports<'react-native-svg/lib/commonjs/lib/extract/extractOpacity'>;
}
declare module 'react-native-svg/lib/commonjs/lib/extract/extractPolyPoints.js' {
  declare module.exports: $Exports<'react-native-svg/lib/commonjs/lib/extract/extractPolyPoints'>;
}
declare module 'react-native-svg/lib/commonjs/lib/extract/extractProps.js' {
  declare module.exports: $Exports<'react-native-svg/lib/commonjs/lib/extract/extractProps'>;
}
declare module 'react-native-svg/lib/commonjs/lib/extract/extractResponder.js' {
  declare module.exports: $Exports<'react-native-svg/lib/commonjs/lib/extract/extractResponder'>;
}
declare module 'react-native-svg/lib/commonjs/lib/extract/extractStroke.js' {
  declare module.exports: $Exports<'react-native-svg/lib/commonjs/lib/extract/extractStroke'>;
}
declare module 'react-native-svg/lib/commonjs/lib/extract/extractText.js' {
  declare module.exports: $Exports<'react-native-svg/lib/commonjs/lib/extract/extractText'>;
}
declare module 'react-native-svg/lib/commonjs/lib/extract/extractTransform.js' {
  declare module.exports: $Exports<'react-native-svg/lib/commonjs/lib/extract/extractTransform'>;
}
declare module 'react-native-svg/lib/commonjs/lib/extract/extractViewBox.js' {
  declare module.exports: $Exports<'react-native-svg/lib/commonjs/lib/extract/extractViewBox'>;
}
declare module 'react-native-svg/lib/commonjs/lib/extract/transform.js' {
  declare module.exports: $Exports<'react-native-svg/lib/commonjs/lib/extract/transform'>;
}
declare module 'react-native-svg/lib/commonjs/lib/extract/types.js' {
  declare module.exports: $Exports<'react-native-svg/lib/commonjs/lib/extract/types'>;
}
declare module 'react-native-svg/lib/commonjs/lib/Matrix2D.js' {
  declare module.exports: $Exports<'react-native-svg/lib/commonjs/lib/Matrix2D'>;
}
declare module 'react-native-svg/lib/commonjs/lib/resolve.js' {
  declare module.exports: $Exports<'react-native-svg/lib/commonjs/lib/resolve'>;
}
declare module 'react-native-svg/lib/commonjs/lib/SvgTouchableMixin.js' {
  declare module.exports: $Exports<'react-native-svg/lib/commonjs/lib/SvgTouchableMixin'>;
}
declare module 'react-native-svg/lib/commonjs/lib/units.js' {
  declare module.exports: $Exports<'react-native-svg/lib/commonjs/lib/units'>;
}
declare module 'react-native-svg/lib/commonjs/lib/util.js' {
  declare module.exports: $Exports<'react-native-svg/lib/commonjs/lib/util'>;
}
declare module 'react-native-svg/lib/commonjs/ReactNativeSVG.js' {
  declare module.exports: $Exports<'react-native-svg/lib/commonjs/ReactNativeSVG'>;
}
declare module 'react-native-svg/lib/commonjs/ReactNativeSVG.web.js' {
  declare module.exports: $Exports<'react-native-svg/lib/commonjs/ReactNativeSVG.web'>;
}
declare module 'react-native-svg/lib/commonjs/xml.js' {
  declare module.exports: $Exports<'react-native-svg/lib/commonjs/xml'>;
}
declare module 'react-native-svg/lib/module/elements/Circle.js' {
  declare module.exports: $Exports<'react-native-svg/lib/module/elements/Circle'>;
}
declare module 'react-native-svg/lib/module/elements/ClipPath.js' {
  declare module.exports: $Exports<'react-native-svg/lib/module/elements/ClipPath'>;
}
declare module 'react-native-svg/lib/module/elements/Defs.js' {
  declare module.exports: $Exports<'react-native-svg/lib/module/elements/Defs'>;
}
declare module 'react-native-svg/lib/module/elements/Ellipse.js' {
  declare module.exports: $Exports<'react-native-svg/lib/module/elements/Ellipse'>;
}
declare module 'react-native-svg/lib/module/elements/G.js' {
  declare module.exports: $Exports<'react-native-svg/lib/module/elements/G'>;
}
declare module 'react-native-svg/lib/module/elements/Image.js' {
  declare module.exports: $Exports<'react-native-svg/lib/module/elements/Image'>;
}
declare module 'react-native-svg/lib/module/elements/Line.js' {
  declare module.exports: $Exports<'react-native-svg/lib/module/elements/Line'>;
}
declare module 'react-native-svg/lib/module/elements/LinearGradient.js' {
  declare module.exports: $Exports<'react-native-svg/lib/module/elements/LinearGradient'>;
}
declare module 'react-native-svg/lib/module/elements/Mask.js' {
  declare module.exports: $Exports<'react-native-svg/lib/module/elements/Mask'>;
}
declare module 'react-native-svg/lib/module/elements/Path.js' {
  declare module.exports: $Exports<'react-native-svg/lib/module/elements/Path'>;
}
declare module 'react-native-svg/lib/module/elements/Pattern.js' {
  declare module.exports: $Exports<'react-native-svg/lib/module/elements/Pattern'>;
}
declare module 'react-native-svg/lib/module/elements/Polygon.js' {
  declare module.exports: $Exports<'react-native-svg/lib/module/elements/Polygon'>;
}
declare module 'react-native-svg/lib/module/elements/Polyline.js' {
  declare module.exports: $Exports<'react-native-svg/lib/module/elements/Polyline'>;
}
declare module 'react-native-svg/lib/module/elements/RadialGradient.js' {
  declare module.exports: $Exports<'react-native-svg/lib/module/elements/RadialGradient'>;
}
declare module 'react-native-svg/lib/module/elements/Rect.js' {
  declare module.exports: $Exports<'react-native-svg/lib/module/elements/Rect'>;
}
declare module 'react-native-svg/lib/module/elements/Shape.js' {
  declare module.exports: $Exports<'react-native-svg/lib/module/elements/Shape'>;
}
declare module 'react-native-svg/lib/module/elements/Stop.js' {
  declare module.exports: $Exports<'react-native-svg/lib/module/elements/Stop'>;
}
declare module 'react-native-svg/lib/module/elements/Svg.js' {
  declare module.exports: $Exports<'react-native-svg/lib/module/elements/Svg'>;
}
declare module 'react-native-svg/lib/module/elements/Symbol.js' {
  declare module.exports: $Exports<'react-native-svg/lib/module/elements/Symbol'>;
}
declare module 'react-native-svg/lib/module/elements/Text.js' {
  declare module.exports: $Exports<'react-native-svg/lib/module/elements/Text'>;
}
declare module 'react-native-svg/lib/module/elements/TextPath.js' {
  declare module.exports: $Exports<'react-native-svg/lib/module/elements/TextPath'>;
}
declare module 'react-native-svg/lib/module/elements/TSpan.js' {
  declare module.exports: $Exports<'react-native-svg/lib/module/elements/TSpan'>;
}
declare module 'react-native-svg/lib/module/elements/Use.js' {
  declare module.exports: $Exports<'react-native-svg/lib/module/elements/Use'>;
}
declare module 'react-native-svg/lib/module/index.d.js' {
  declare module.exports: $Exports<'react-native-svg/lib/module/index.d'>;
}
declare module 'react-native-svg/lib/module/index' {
  declare module.exports: $Exports<'react-native-svg/lib/module'>;
}
declare module 'react-native-svg/lib/module/index.js' {
  declare module.exports: $Exports<'react-native-svg/lib/module'>;
}
declare module 'react-native-svg/lib/module/lib/extract/extractBrush.js' {
  declare module.exports: $Exports<'react-native-svg/lib/module/lib/extract/extractBrush'>;
}
declare module 'react-native-svg/lib/module/lib/extract/extractClipPath.js' {
  declare module.exports: $Exports<'react-native-svg/lib/module/lib/extract/extractClipPath'>;
}
declare module 'react-native-svg/lib/module/lib/extract/extractColor.js' {
  declare module.exports: $Exports<'react-native-svg/lib/module/lib/extract/extractColor'>;
}
declare module 'react-native-svg/lib/module/lib/extract/extractFill.js' {
  declare module.exports: $Exports<'react-native-svg/lib/module/lib/extract/extractFill'>;
}
declare module 'react-native-svg/lib/module/lib/extract/extractGradient.js' {
  declare module.exports: $Exports<'react-native-svg/lib/module/lib/extract/extractGradient'>;
}
declare module 'react-native-svg/lib/module/lib/extract/extractLengthList.js' {
  declare module.exports: $Exports<'react-native-svg/lib/module/lib/extract/extractLengthList'>;
}
declare module 'react-native-svg/lib/module/lib/extract/extractOpacity.js' {
  declare module.exports: $Exports<'react-native-svg/lib/module/lib/extract/extractOpacity'>;
}
declare module 'react-native-svg/lib/module/lib/extract/extractPolyPoints.js' {
  declare module.exports: $Exports<'react-native-svg/lib/module/lib/extract/extractPolyPoints'>;
}
declare module 'react-native-svg/lib/module/lib/extract/extractProps.js' {
  declare module.exports: $Exports<'react-native-svg/lib/module/lib/extract/extractProps'>;
}
declare module 'react-native-svg/lib/module/lib/extract/extractResponder.js' {
  declare module.exports: $Exports<'react-native-svg/lib/module/lib/extract/extractResponder'>;
}
declare module 'react-native-svg/lib/module/lib/extract/extractStroke.js' {
  declare module.exports: $Exports<'react-native-svg/lib/module/lib/extract/extractStroke'>;
}
declare module 'react-native-svg/lib/module/lib/extract/extractText.js' {
  declare module.exports: $Exports<'react-native-svg/lib/module/lib/extract/extractText'>;
}
declare module 'react-native-svg/lib/module/lib/extract/extractTransform.js' {
  declare module.exports: $Exports<'react-native-svg/lib/module/lib/extract/extractTransform'>;
}
declare module 'react-native-svg/lib/module/lib/extract/extractViewBox.js' {
  declare module.exports: $Exports<'react-native-svg/lib/module/lib/extract/extractViewBox'>;
}
declare module 'react-native-svg/lib/module/lib/extract/transform.js' {
  declare module.exports: $Exports<'react-native-svg/lib/module/lib/extract/transform'>;
}
declare module 'react-native-svg/lib/module/lib/extract/types.js' {
  declare module.exports: $Exports<'react-native-svg/lib/module/lib/extract/types'>;
}
declare module 'react-native-svg/lib/module/lib/Matrix2D.js' {
  declare module.exports: $Exports<'react-native-svg/lib/module/lib/Matrix2D'>;
}
declare module 'react-native-svg/lib/module/lib/resolve.js' {
  declare module.exports: $Exports<'react-native-svg/lib/module/lib/resolve'>;
}
declare module 'react-native-svg/lib/module/lib/SvgTouchableMixin.js' {
  declare module.exports: $Exports<'react-native-svg/lib/module/lib/SvgTouchableMixin'>;
}
declare module 'react-native-svg/lib/module/lib/units.js' {
  declare module.exports: $Exports<'react-native-svg/lib/module/lib/units'>;
}
declare module 'react-native-svg/lib/module/lib/util.js' {
  declare module.exports: $Exports<'react-native-svg/lib/module/lib/util'>;
}
declare module 'react-native-svg/lib/module/ReactNativeSVG.js' {
  declare module.exports: $Exports<'react-native-svg/lib/module/ReactNativeSVG'>;
}
declare module 'react-native-svg/lib/module/ReactNativeSVG.web.js' {
  declare module.exports: $Exports<'react-native-svg/lib/module/ReactNativeSVG.web'>;
}
declare module 'react-native-svg/lib/module/xml.js' {
  declare module.exports: $Exports<'react-native-svg/lib/module/xml'>;
}
declare module 'react-native-svg/src/lib/extract/transform.js' {
  declare module.exports: $Exports<'react-native-svg/src/lib/extract/transform'>;
}
