// flow-typed signature: e235f7c2f9938b5d5c3c8b42a184ecf6
// flow-typed version: <<STUB>>/react-navigation-tabs_v^2.4.2/flow_v0.104.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-navigation-tabs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-navigation-tabs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-navigation-tabs/lib/commonjs' {
  declare module.exports: any;
}

declare module 'react-navigation-tabs/lib/commonjs/navigators/createBottomTabNavigator' {
  declare module.exports: any;
}

declare module 'react-navigation-tabs/lib/commonjs/navigators/createMaterialTopTabNavigator' {
  declare module.exports: any;
}

declare module 'react-navigation-tabs/lib/commonjs/types' {
  declare module.exports: any;
}

declare module 'react-navigation-tabs/lib/commonjs/utils/createTabNavigator' {
  declare module.exports: any;
}

declare module 'react-navigation-tabs/lib/commonjs/utils/withDimensions' {
  declare module.exports: any;
}

declare module 'react-navigation-tabs/lib/commonjs/views/BottomTabBar' {
  declare module.exports: any;
}

declare module 'react-navigation-tabs/lib/commonjs/views/CrossFadeIcon' {
  declare module.exports: any;
}

declare module 'react-navigation-tabs/lib/commonjs/views/MaterialTopTabBar' {
  declare module.exports: any;
}

declare module 'react-navigation-tabs/lib/commonjs/views/ResourceSavingScene' {
  declare module.exports: any;
}

declare module 'react-navigation-tabs/lib/module' {
  declare module.exports: any;
}

declare module 'react-navigation-tabs/lib/module/navigators/createBottomTabNavigator' {
  declare module.exports: any;
}

declare module 'react-navigation-tabs/lib/module/navigators/createMaterialTopTabNavigator' {
  declare module.exports: any;
}

declare module 'react-navigation-tabs/lib/module/types' {
  declare module.exports: any;
}

declare module 'react-navigation-tabs/lib/module/utils/createTabNavigator' {
  declare module.exports: any;
}

declare module 'react-navigation-tabs/lib/module/utils/withDimensions' {
  declare module.exports: any;
}

declare module 'react-navigation-tabs/lib/module/views/BottomTabBar' {
  declare module.exports: any;
}

declare module 'react-navigation-tabs/lib/module/views/CrossFadeIcon' {
  declare module.exports: any;
}

declare module 'react-navigation-tabs/lib/module/views/MaterialTopTabBar' {
  declare module.exports: any;
}

declare module 'react-navigation-tabs/lib/module/views/ResourceSavingScene' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-navigation-tabs/lib/commonjs/index' {
  declare module.exports: $Exports<'react-navigation-tabs/lib/commonjs'>;
}
declare module 'react-navigation-tabs/lib/commonjs/index.js' {
  declare module.exports: $Exports<'react-navigation-tabs/lib/commonjs'>;
}
declare module 'react-navigation-tabs/lib/commonjs/navigators/createBottomTabNavigator.js' {
  declare module.exports: $Exports<'react-navigation-tabs/lib/commonjs/navigators/createBottomTabNavigator'>;
}
declare module 'react-navigation-tabs/lib/commonjs/navigators/createMaterialTopTabNavigator.js' {
  declare module.exports: $Exports<'react-navigation-tabs/lib/commonjs/navigators/createMaterialTopTabNavigator'>;
}
declare module 'react-navigation-tabs/lib/commonjs/types.js' {
  declare module.exports: $Exports<'react-navigation-tabs/lib/commonjs/types'>;
}
declare module 'react-navigation-tabs/lib/commonjs/utils/createTabNavigator.js' {
  declare module.exports: $Exports<'react-navigation-tabs/lib/commonjs/utils/createTabNavigator'>;
}
declare module 'react-navigation-tabs/lib/commonjs/utils/withDimensions.js' {
  declare module.exports: $Exports<'react-navigation-tabs/lib/commonjs/utils/withDimensions'>;
}
declare module 'react-navigation-tabs/lib/commonjs/views/BottomTabBar.js' {
  declare module.exports: $Exports<'react-navigation-tabs/lib/commonjs/views/BottomTabBar'>;
}
declare module 'react-navigation-tabs/lib/commonjs/views/CrossFadeIcon.js' {
  declare module.exports: $Exports<'react-navigation-tabs/lib/commonjs/views/CrossFadeIcon'>;
}
declare module 'react-navigation-tabs/lib/commonjs/views/MaterialTopTabBar.js' {
  declare module.exports: $Exports<'react-navigation-tabs/lib/commonjs/views/MaterialTopTabBar'>;
}
declare module 'react-navigation-tabs/lib/commonjs/views/ResourceSavingScene.js' {
  declare module.exports: $Exports<'react-navigation-tabs/lib/commonjs/views/ResourceSavingScene'>;
}
declare module 'react-navigation-tabs/lib/module/index' {
  declare module.exports: $Exports<'react-navigation-tabs/lib/module'>;
}
declare module 'react-navigation-tabs/lib/module/index.js' {
  declare module.exports: $Exports<'react-navigation-tabs/lib/module'>;
}
declare module 'react-navigation-tabs/lib/module/navigators/createBottomTabNavigator.js' {
  declare module.exports: $Exports<'react-navigation-tabs/lib/module/navigators/createBottomTabNavigator'>;
}
declare module 'react-navigation-tabs/lib/module/navigators/createMaterialTopTabNavigator.js' {
  declare module.exports: $Exports<'react-navigation-tabs/lib/module/navigators/createMaterialTopTabNavigator'>;
}
declare module 'react-navigation-tabs/lib/module/types.js' {
  declare module.exports: $Exports<'react-navigation-tabs/lib/module/types'>;
}
declare module 'react-navigation-tabs/lib/module/utils/createTabNavigator.js' {
  declare module.exports: $Exports<'react-navigation-tabs/lib/module/utils/createTabNavigator'>;
}
declare module 'react-navigation-tabs/lib/module/utils/withDimensions.js' {
  declare module.exports: $Exports<'react-navigation-tabs/lib/module/utils/withDimensions'>;
}
declare module 'react-navigation-tabs/lib/module/views/BottomTabBar.js' {
  declare module.exports: $Exports<'react-navigation-tabs/lib/module/views/BottomTabBar'>;
}
declare module 'react-navigation-tabs/lib/module/views/CrossFadeIcon.js' {
  declare module.exports: $Exports<'react-navigation-tabs/lib/module/views/CrossFadeIcon'>;
}
declare module 'react-navigation-tabs/lib/module/views/MaterialTopTabBar.js' {
  declare module.exports: $Exports<'react-navigation-tabs/lib/module/views/MaterialTopTabBar'>;
}
declare module 'react-navigation-tabs/lib/module/views/ResourceSavingScene.js' {
  declare module.exports: $Exports<'react-navigation-tabs/lib/module/views/ResourceSavingScene'>;
}
