// flow-typed signature: 0a13cd10a65549283f50abc4953edabc
// flow-typed version: <<STUB>>/react-native-redash_v^10.0.1/flow_v0.120.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-redash'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-redash' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-redash/lib/module/__mocks__/react-native-reanimated' {
  declare module.exports: any;
}

declare module 'react-native-redash/lib/module/AnimationRunners' {
  declare module.exports: any;
}

declare module 'react-native-redash/lib/module/Animations' {
  declare module.exports: any;
}

declare module 'react-native-redash/lib/module/Array' {
  declare module.exports: any;
}

declare module 'react-native-redash/lib/module/bezier/CubicBezierLength' {
  declare module.exports: any;
}

declare module 'react-native-redash/lib/module/bezier/CubicBezierSolve' {
  declare module.exports: any;
}

declare module 'react-native-redash/lib/module/Colors' {
  declare module.exports: any;
}

declare module 'react-native-redash/lib/module/Coordinates' {
  declare module.exports: any;
}

declare module 'react-native-redash/lib/module/Gesture' {
  declare module.exports: any;
}

declare module 'react-native-redash/lib/module/index.d' {
  declare module.exports: any;
}

declare module 'react-native-redash/lib/module' {
  declare module.exports: any;
}

declare module 'react-native-redash/lib/module/Math' {
  declare module.exports: any;
}

declare module 'react-native-redash/lib/module/ReText' {
  declare module.exports: any;
}

declare module 'react-native-redash/lib/module/String' {
  declare module.exports: any;
}

declare module 'react-native-redash/lib/module/SVG' {
  declare module.exports: any;
}

declare module 'react-native-redash/lib/module/Transformations' {
  declare module.exports: any;
}

declare module 'react-native-redash/lib/module/Transitions' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-redash/lib/module/__mocks__/react-native-reanimated.js' {
  declare module.exports: $Exports<'react-native-redash/lib/module/__mocks__/react-native-reanimated'>;
}
declare module 'react-native-redash/lib/module/AnimationRunners.js' {
  declare module.exports: $Exports<'react-native-redash/lib/module/AnimationRunners'>;
}
declare module 'react-native-redash/lib/module/Animations.js' {
  declare module.exports: $Exports<'react-native-redash/lib/module/Animations'>;
}
declare module 'react-native-redash/lib/module/Array.js' {
  declare module.exports: $Exports<'react-native-redash/lib/module/Array'>;
}
declare module 'react-native-redash/lib/module/bezier/CubicBezierLength.js' {
  declare module.exports: $Exports<'react-native-redash/lib/module/bezier/CubicBezierLength'>;
}
declare module 'react-native-redash/lib/module/bezier/CubicBezierSolve.js' {
  declare module.exports: $Exports<'react-native-redash/lib/module/bezier/CubicBezierSolve'>;
}
declare module 'react-native-redash/lib/module/Colors.js' {
  declare module.exports: $Exports<'react-native-redash/lib/module/Colors'>;
}
declare module 'react-native-redash/lib/module/Coordinates.js' {
  declare module.exports: $Exports<'react-native-redash/lib/module/Coordinates'>;
}
declare module 'react-native-redash/lib/module/Gesture.js' {
  declare module.exports: $Exports<'react-native-redash/lib/module/Gesture'>;
}
declare module 'react-native-redash/lib/module/index.d.js' {
  declare module.exports: $Exports<'react-native-redash/lib/module/index.d'>;
}
declare module 'react-native-redash/lib/module/index' {
  declare module.exports: $Exports<'react-native-redash/lib/module'>;
}
declare module 'react-native-redash/lib/module/index.js' {
  declare module.exports: $Exports<'react-native-redash/lib/module'>;
}
declare module 'react-native-redash/lib/module/Math.js' {
  declare module.exports: $Exports<'react-native-redash/lib/module/Math'>;
}
declare module 'react-native-redash/lib/module/ReText.js' {
  declare module.exports: $Exports<'react-native-redash/lib/module/ReText'>;
}
declare module 'react-native-redash/lib/module/String.js' {
  declare module.exports: $Exports<'react-native-redash/lib/module/String'>;
}
declare module 'react-native-redash/lib/module/SVG.js' {
  declare module.exports: $Exports<'react-native-redash/lib/module/SVG'>;
}
declare module 'react-native-redash/lib/module/Transformations.js' {
  declare module.exports: $Exports<'react-native-redash/lib/module/Transformations'>;
}
declare module 'react-native-redash/lib/module/Transitions.js' {
  declare module.exports: $Exports<'react-native-redash/lib/module/Transitions'>;
}
