// flow-typed signature: 7ee29f7c06d355fd7c50c7134a674d5c
// flow-typed version: <<STUB>>/react-native-modal_v^11.5.3/flow_v0.112.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-modal'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-modal' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-modal/dist' {
  declare module.exports: any;
}

declare module 'react-native-modal/dist/modal' {
  declare module.exports: any;
}

declare module 'react-native-modal/dist/modal.style' {
  declare module.exports: any;
}

declare module 'react-native-modal/dist/types' {
  declare module.exports: any;
}

declare module 'react-native-modal/dist/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-modal/dist/index' {
  declare module.exports: $Exports<'react-native-modal/dist'>;
}
declare module 'react-native-modal/dist/index.js' {
  declare module.exports: $Exports<'react-native-modal/dist'>;
}
declare module 'react-native-modal/dist/modal.js' {
  declare module.exports: $Exports<'react-native-modal/dist/modal'>;
}
declare module 'react-native-modal/dist/modal.style.js' {
  declare module.exports: $Exports<'react-native-modal/dist/modal.style'>;
}
declare module 'react-native-modal/dist/types.js' {
  declare module.exports: $Exports<'react-native-modal/dist/types'>;
}
declare module 'react-native-modal/dist/utils.js' {
  declare module.exports: $Exports<'react-native-modal/dist/utils'>;
}
