// flow-typed signature: ab1de20e6595af526e98e4a9e3164555
// flow-typed version: <<STUB>>/react-navigation-drawer_v^2.1.2/flow_v0.104.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-navigation-drawer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-navigation-drawer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-navigation-drawer/lib/commonjs' {
  declare module.exports: any;
}

declare module 'react-navigation-drawer/lib/commonjs/navigators/__tests__/createDrawerNavigator.test' {
  declare module.exports: any;
}

declare module 'react-navigation-drawer/lib/commonjs/navigators/createDrawerNavigator' {
  declare module.exports: any;
}

declare module 'react-navigation-drawer/lib/commonjs/routers/__tests__/DrawerRouter.test' {
  declare module.exports: any;
}

declare module 'react-navigation-drawer/lib/commonjs/routers/DrawerActions' {
  declare module.exports: any;
}

declare module 'react-navigation-drawer/lib/commonjs/routers/DrawerRouter' {
  declare module.exports: any;
}

declare module 'react-navigation-drawer/lib/commonjs/types' {
  declare module.exports: any;
}

declare module 'react-navigation-drawer/lib/commonjs/utils/DrawerGestureContext' {
  declare module.exports: any;
}

declare module 'react-navigation-drawer/lib/commonjs/views/Drawer' {
  declare module.exports: any;
}

declare module 'react-navigation-drawer/lib/commonjs/views/DrawerNavigatorItems' {
  declare module.exports: any;
}

declare module 'react-navigation-drawer/lib/commonjs/views/DrawerSidebar' {
  declare module.exports: any;
}

declare module 'react-navigation-drawer/lib/commonjs/views/DrawerView' {
  declare module.exports: any;
}

declare module 'react-navigation-drawer/lib/commonjs/views/ResourceSavingScene' {
  declare module.exports: any;
}

declare module 'react-navigation-drawer/lib/commonjs/views/TouchableItem' {
  declare module.exports: any;
}

declare module 'react-navigation-drawer/lib/module' {
  declare module.exports: any;
}

declare module 'react-navigation-drawer/lib/module/navigators/__tests__/createDrawerNavigator.test' {
  declare module.exports: any;
}

declare module 'react-navigation-drawer/lib/module/navigators/createDrawerNavigator' {
  declare module.exports: any;
}

declare module 'react-navigation-drawer/lib/module/routers/__tests__/DrawerRouter.test' {
  declare module.exports: any;
}

declare module 'react-navigation-drawer/lib/module/routers/DrawerActions' {
  declare module.exports: any;
}

declare module 'react-navigation-drawer/lib/module/routers/DrawerRouter' {
  declare module.exports: any;
}

declare module 'react-navigation-drawer/lib/module/types' {
  declare module.exports: any;
}

declare module 'react-navigation-drawer/lib/module/utils/DrawerGestureContext' {
  declare module.exports: any;
}

declare module 'react-navigation-drawer/lib/module/views/Drawer' {
  declare module.exports: any;
}

declare module 'react-navigation-drawer/lib/module/views/DrawerNavigatorItems' {
  declare module.exports: any;
}

declare module 'react-navigation-drawer/lib/module/views/DrawerSidebar' {
  declare module.exports: any;
}

declare module 'react-navigation-drawer/lib/module/views/DrawerView' {
  declare module.exports: any;
}

declare module 'react-navigation-drawer/lib/module/views/ResourceSavingScene' {
  declare module.exports: any;
}

declare module 'react-navigation-drawer/lib/module/views/TouchableItem' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-navigation-drawer/lib/commonjs/index' {
  declare module.exports: $Exports<'react-navigation-drawer/lib/commonjs'>;
}
declare module 'react-navigation-drawer/lib/commonjs/index.js' {
  declare module.exports: $Exports<'react-navigation-drawer/lib/commonjs'>;
}
declare module 'react-navigation-drawer/lib/commonjs/navigators/__tests__/createDrawerNavigator.test.js' {
  declare module.exports: $Exports<'react-navigation-drawer/lib/commonjs/navigators/__tests__/createDrawerNavigator.test'>;
}
declare module 'react-navigation-drawer/lib/commonjs/navigators/createDrawerNavigator.js' {
  declare module.exports: $Exports<'react-navigation-drawer/lib/commonjs/navigators/createDrawerNavigator'>;
}
declare module 'react-navigation-drawer/lib/commonjs/routers/__tests__/DrawerRouter.test.js' {
  declare module.exports: $Exports<'react-navigation-drawer/lib/commonjs/routers/__tests__/DrawerRouter.test'>;
}
declare module 'react-navigation-drawer/lib/commonjs/routers/DrawerActions.js' {
  declare module.exports: $Exports<'react-navigation-drawer/lib/commonjs/routers/DrawerActions'>;
}
declare module 'react-navigation-drawer/lib/commonjs/routers/DrawerRouter.js' {
  declare module.exports: $Exports<'react-navigation-drawer/lib/commonjs/routers/DrawerRouter'>;
}
declare module 'react-navigation-drawer/lib/commonjs/types.js' {
  declare module.exports: $Exports<'react-navigation-drawer/lib/commonjs/types'>;
}
declare module 'react-navigation-drawer/lib/commonjs/utils/DrawerGestureContext.js' {
  declare module.exports: $Exports<'react-navigation-drawer/lib/commonjs/utils/DrawerGestureContext'>;
}
declare module 'react-navigation-drawer/lib/commonjs/views/Drawer.js' {
  declare module.exports: $Exports<'react-navigation-drawer/lib/commonjs/views/Drawer'>;
}
declare module 'react-navigation-drawer/lib/commonjs/views/DrawerNavigatorItems.js' {
  declare module.exports: $Exports<'react-navigation-drawer/lib/commonjs/views/DrawerNavigatorItems'>;
}
declare module 'react-navigation-drawer/lib/commonjs/views/DrawerSidebar.js' {
  declare module.exports: $Exports<'react-navigation-drawer/lib/commonjs/views/DrawerSidebar'>;
}
declare module 'react-navigation-drawer/lib/commonjs/views/DrawerView.js' {
  declare module.exports: $Exports<'react-navigation-drawer/lib/commonjs/views/DrawerView'>;
}
declare module 'react-navigation-drawer/lib/commonjs/views/ResourceSavingScene.js' {
  declare module.exports: $Exports<'react-navigation-drawer/lib/commonjs/views/ResourceSavingScene'>;
}
declare module 'react-navigation-drawer/lib/commonjs/views/TouchableItem.js' {
  declare module.exports: $Exports<'react-navigation-drawer/lib/commonjs/views/TouchableItem'>;
}
declare module 'react-navigation-drawer/lib/module/index' {
  declare module.exports: $Exports<'react-navigation-drawer/lib/module'>;
}
declare module 'react-navigation-drawer/lib/module/index.js' {
  declare module.exports: $Exports<'react-navigation-drawer/lib/module'>;
}
declare module 'react-navigation-drawer/lib/module/navigators/__tests__/createDrawerNavigator.test.js' {
  declare module.exports: $Exports<'react-navigation-drawer/lib/module/navigators/__tests__/createDrawerNavigator.test'>;
}
declare module 'react-navigation-drawer/lib/module/navigators/createDrawerNavigator.js' {
  declare module.exports: $Exports<'react-navigation-drawer/lib/module/navigators/createDrawerNavigator'>;
}
declare module 'react-navigation-drawer/lib/module/routers/__tests__/DrawerRouter.test.js' {
  declare module.exports: $Exports<'react-navigation-drawer/lib/module/routers/__tests__/DrawerRouter.test'>;
}
declare module 'react-navigation-drawer/lib/module/routers/DrawerActions.js' {
  declare module.exports: $Exports<'react-navigation-drawer/lib/module/routers/DrawerActions'>;
}
declare module 'react-navigation-drawer/lib/module/routers/DrawerRouter.js' {
  declare module.exports: $Exports<'react-navigation-drawer/lib/module/routers/DrawerRouter'>;
}
declare module 'react-navigation-drawer/lib/module/types.js' {
  declare module.exports: $Exports<'react-navigation-drawer/lib/module/types'>;
}
declare module 'react-navigation-drawer/lib/module/utils/DrawerGestureContext.js' {
  declare module.exports: $Exports<'react-navigation-drawer/lib/module/utils/DrawerGestureContext'>;
}
declare module 'react-navigation-drawer/lib/module/views/Drawer.js' {
  declare module.exports: $Exports<'react-navigation-drawer/lib/module/views/Drawer'>;
}
declare module 'react-navigation-drawer/lib/module/views/DrawerNavigatorItems.js' {
  declare module.exports: $Exports<'react-navigation-drawer/lib/module/views/DrawerNavigatorItems'>;
}
declare module 'react-navigation-drawer/lib/module/views/DrawerSidebar.js' {
  declare module.exports: $Exports<'react-navigation-drawer/lib/module/views/DrawerSidebar'>;
}
declare module 'react-navigation-drawer/lib/module/views/DrawerView.js' {
  declare module.exports: $Exports<'react-navigation-drawer/lib/module/views/DrawerView'>;
}
declare module 'react-navigation-drawer/lib/module/views/ResourceSavingScene.js' {
  declare module.exports: $Exports<'react-navigation-drawer/lib/module/views/ResourceSavingScene'>;
}
declare module 'react-navigation-drawer/lib/module/views/TouchableItem.js' {
  declare module.exports: $Exports<'react-navigation-drawer/lib/module/views/TouchableItem'>;
}
