// flow-typed signature: 3a999f0e815a78b22e7c4de7920e18df
// flow-typed version: <<STUB>>/react-native-easy-toast_v^1.2.0/flow_v0.98.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-easy-toast'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-easy-toast' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-native-easy-toast/index' {
  declare module.exports: $Exports<'react-native-easy-toast'>;
}
declare module 'react-native-easy-toast/index.js' {
  declare module.exports: $Exports<'react-native-easy-toast'>;
}
