// flow-typed signature: 1485e94255c8df5aaa9fa077a39fb3bf
// flow-typed version: <<STUB>>/react-native-dropdownalert_v^4.2.1/flow_v0.112.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-dropdownalert'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-dropdownalert' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-dropdownalert/babel.config' {
  declare module.exports: any;
}

declare module 'react-native-dropdownalert/CancelButton' {
  declare module.exports: any;
}

declare module 'react-native-dropdownalert/constants' {
  declare module.exports: any;
}

declare module 'react-native-dropdownalert/DropdownAlert' {
  declare module.exports: any;
}

declare module 'react-native-dropdownalert/imageview' {
  declare module.exports: any;
}

declare module 'react-native-dropdownalert/jest.config' {
  declare module.exports: any;
}

declare module 'react-native-dropdownalert/TextView' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-dropdownalert/babel.config.js' {
  declare module.exports: $Exports<'react-native-dropdownalert/babel.config'>;
}
declare module 'react-native-dropdownalert/CancelButton.js' {
  declare module.exports: $Exports<'react-native-dropdownalert/CancelButton'>;
}
declare module 'react-native-dropdownalert/constants.js' {
  declare module.exports: $Exports<'react-native-dropdownalert/constants'>;
}
declare module 'react-native-dropdownalert/DropdownAlert.js' {
  declare module.exports: $Exports<'react-native-dropdownalert/DropdownAlert'>;
}
declare module 'react-native-dropdownalert/imageview.js' {
  declare module.exports: $Exports<'react-native-dropdownalert/imageview'>;
}
declare module 'react-native-dropdownalert/jest.config.js' {
  declare module.exports: $Exports<'react-native-dropdownalert/jest.config'>;
}
declare module 'react-native-dropdownalert/TextView.js' {
  declare module.exports: $Exports<'react-native-dropdownalert/TextView'>;
}
