// flow-typed signature: 0f284359e36ad8fab7b7097724006cf2
// flow-typed version: <<STUB>>/rn-placeholder_v^3.0.0/flow_v0.104.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rn-placeholder'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rn-placeholder' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rn-placeholder/lib/animations/AnimationConsumer' {
  declare module.exports: any;
}

declare module 'rn-placeholder/lib/animations/context' {
  declare module.exports: any;
}

declare module 'rn-placeholder/lib/animations/Fade' {
  declare module.exports: any;
}

declare module 'rn-placeholder/lib/animations/Loader' {
  declare module.exports: any;
}

declare module 'rn-placeholder/lib/animations/Progressive' {
  declare module.exports: any;
}

declare module 'rn-placeholder/lib/animations/Raw' {
  declare module.exports: any;
}

declare module 'rn-placeholder/lib/animations/Shine' {
  declare module.exports: any;
}

declare module 'rn-placeholder/lib/animations/ShineOverlay' {
  declare module.exports: any;
}

declare module 'rn-placeholder/lib' {
  declare module.exports: any;
}

declare module 'rn-placeholder/lib/Placeholder' {
  declare module.exports: any;
}

declare module 'rn-placeholder/lib/PlaceholderLine' {
  declare module.exports: any;
}

declare module 'rn-placeholder/lib/PlaceholderMedia' {
  declare module.exports: any;
}

declare module 'rn-placeholder/lib/tokens' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rn-placeholder/lib/animations/AnimationConsumer.js' {
  declare module.exports: $Exports<'rn-placeholder/lib/animations/AnimationConsumer'>;
}
declare module 'rn-placeholder/lib/animations/context.js' {
  declare module.exports: $Exports<'rn-placeholder/lib/animations/context'>;
}
declare module 'rn-placeholder/lib/animations/Fade.js' {
  declare module.exports: $Exports<'rn-placeholder/lib/animations/Fade'>;
}
declare module 'rn-placeholder/lib/animations/Loader.js' {
  declare module.exports: $Exports<'rn-placeholder/lib/animations/Loader'>;
}
declare module 'rn-placeholder/lib/animations/Progressive.js' {
  declare module.exports: $Exports<'rn-placeholder/lib/animations/Progressive'>;
}
declare module 'rn-placeholder/lib/animations/Raw.js' {
  declare module.exports: $Exports<'rn-placeholder/lib/animations/Raw'>;
}
declare module 'rn-placeholder/lib/animations/Shine.js' {
  declare module.exports: $Exports<'rn-placeholder/lib/animations/Shine'>;
}
declare module 'rn-placeholder/lib/animations/ShineOverlay.js' {
  declare module.exports: $Exports<'rn-placeholder/lib/animations/ShineOverlay'>;
}
declare module 'rn-placeholder/lib/index' {
  declare module.exports: $Exports<'rn-placeholder/lib'>;
}
declare module 'rn-placeholder/lib/index.js' {
  declare module.exports: $Exports<'rn-placeholder/lib'>;
}
declare module 'rn-placeholder/lib/Placeholder.js' {
  declare module.exports: $Exports<'rn-placeholder/lib/Placeholder'>;
}
declare module 'rn-placeholder/lib/PlaceholderLine.js' {
  declare module.exports: $Exports<'rn-placeholder/lib/PlaceholderLine'>;
}
declare module 'rn-placeholder/lib/PlaceholderMedia.js' {
  declare module.exports: $Exports<'rn-placeholder/lib/PlaceholderMedia'>;
}
declare module 'rn-placeholder/lib/tokens.js' {
  declare module.exports: $Exports<'rn-placeholder/lib/tokens'>;
}
