// flow-typed signature: 04a86d290664f200c678b1435d4a7cd3
// flow-typed version: <<STUB>>/rn-placeholder_v^2.0.0/flow_v0.98.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rn-placeholder'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rn-placeholder' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rn-placeholder/babel.config' {
  declare module.exports: any;
}

declare module 'rn-placeholder/coverage/lcov-report/block-navigation' {
  declare module.exports: any;
}

declare module 'rn-placeholder/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'rn-placeholder/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

declare module 'rn-placeholder/setup/test.setup' {
  declare module.exports: any;
}

declare module 'rn-placeholder/src/animation/animations' {
  declare module.exports: any;
}

declare module 'rn-placeholder/src/animation/fade' {
  declare module.exports: any;
}

declare module 'rn-placeholder/src/animation/shine' {
  declare module.exports: any;
}

declare module 'rn-placeholder/src/connect' {
  declare module.exports: any;
}

declare module 'rn-placeholder/src/imageContent/imageContent' {
  declare module.exports: any;
}

declare module 'rn-placeholder/src/index' {
  declare module.exports: any;
}

declare module 'rn-placeholder/src/line/line' {
  declare module.exports: any;
}

declare module 'rn-placeholder/src/paragraph/paragraph' {
  declare module.exports: any;
}

declare module 'rn-placeholder/src/placeholder/placeholder' {
  declare module.exports: any;
}

declare module 'rn-placeholder/src/shapes/box/box.style' {
  declare module.exports: any;
}

declare module 'rn-placeholder/src/shapes/index' {
  declare module.exports: any;
}

declare module 'rn-placeholder/src/shapes/media/media.style' {
  declare module.exports: any;
}

declare module 'rn-placeholder/src/shapes/stylify' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rn-placeholder/babel.config.js' {
  declare module.exports: $Exports<'rn-placeholder/babel.config'>;
}
declare module 'rn-placeholder/coverage/lcov-report/block-navigation.js' {
  declare module.exports: $Exports<'rn-placeholder/coverage/lcov-report/block-navigation'>;
}
declare module 'rn-placeholder/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'rn-placeholder/coverage/lcov-report/prettify'>;
}
declare module 'rn-placeholder/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'rn-placeholder/coverage/lcov-report/sorter'>;
}
declare module 'rn-placeholder/setup/test.setup.js' {
  declare module.exports: $Exports<'rn-placeholder/setup/test.setup'>;
}
declare module 'rn-placeholder/src/animation/animations.js' {
  declare module.exports: $Exports<'rn-placeholder/src/animation/animations'>;
}
declare module 'rn-placeholder/src/animation/fade.js' {
  declare module.exports: $Exports<'rn-placeholder/src/animation/fade'>;
}
declare module 'rn-placeholder/src/animation/shine.js' {
  declare module.exports: $Exports<'rn-placeholder/src/animation/shine'>;
}
declare module 'rn-placeholder/src/connect.js' {
  declare module.exports: $Exports<'rn-placeholder/src/connect'>;
}
declare module 'rn-placeholder/src/imageContent/imageContent.js' {
  declare module.exports: $Exports<'rn-placeholder/src/imageContent/imageContent'>;
}
declare module 'rn-placeholder/src/index.js' {
  declare module.exports: $Exports<'rn-placeholder/src/index'>;
}
declare module 'rn-placeholder/src/line/line.js' {
  declare module.exports: $Exports<'rn-placeholder/src/line/line'>;
}
declare module 'rn-placeholder/src/paragraph/paragraph.js' {
  declare module.exports: $Exports<'rn-placeholder/src/paragraph/paragraph'>;
}
declare module 'rn-placeholder/src/placeholder/placeholder.js' {
  declare module.exports: $Exports<'rn-placeholder/src/placeholder/placeholder'>;
}
declare module 'rn-placeholder/src/shapes/box/box.style.js' {
  declare module.exports: $Exports<'rn-placeholder/src/shapes/box/box.style'>;
}
declare module 'rn-placeholder/src/shapes/index.js' {
  declare module.exports: $Exports<'rn-placeholder/src/shapes/index'>;
}
declare module 'rn-placeholder/src/shapes/media/media.style.js' {
  declare module.exports: $Exports<'rn-placeholder/src/shapes/media/media.style'>;
}
declare module 'rn-placeholder/src/shapes/stylify.js' {
  declare module.exports: $Exports<'rn-placeholder/src/shapes/stylify'>;
}
