// flow-typed signature: 5e1f96994a565e77994c5d055b46c4e5
// flow-typed version: <<STUB>>/@react-native-community/checkbox_v^0.1.0/flow_v0.104.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@react-native-community/checkbox'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@react-native-community/checkbox' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@react-native-community/checkbox/js/__test__/CheckBox.test' {
  declare module.exports: any;
}

declare module '@react-native-community/checkbox/js/AndroidCheckBoxNativeComponent' {
  declare module.exports: any;
}

declare module '@react-native-community/checkbox/js/CheckBox.android' {
  declare module.exports: any;
}

declare module '@react-native-community/checkbox/js/CheckBox.ios' {
  declare module.exports: any;
}

// Filename aliases
declare module '@react-native-community/checkbox/index' {
  declare module.exports: $Exports<'@react-native-community/checkbox'>;
}
declare module '@react-native-community/checkbox/index.js' {
  declare module.exports: $Exports<'@react-native-community/checkbox'>;
}
declare module '@react-native-community/checkbox/js/__test__/CheckBox.test.js' {
  declare module.exports: $Exports<'@react-native-community/checkbox/js/__test__/CheckBox.test'>;
}
declare module '@react-native-community/checkbox/js/AndroidCheckBoxNativeComponent.js' {
  declare module.exports: $Exports<'@react-native-community/checkbox/js/AndroidCheckBoxNativeComponent'>;
}
declare module '@react-native-community/checkbox/js/CheckBox.android.js' {
  declare module.exports: $Exports<'@react-native-community/checkbox/js/CheckBox.android'>;
}
declare module '@react-native-community/checkbox/js/CheckBox.ios.js' {
  declare module.exports: $Exports<'@react-native-community/checkbox/js/CheckBox.ios'>;
}
